//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductSolds = new HashSet<ProductSold>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int P_ID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string Features { get; set; }
        public int SubCategoryID { get; set; }
        public decimal VAT { get; set; }
        public decimal ST { get; set; }
        public decimal Discount { get; set; }
        public decimal Price { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<ProductSold> ProductSolds { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual Temp_Stock Temp_Stock { get; set; }
    }
}
